### ISSUE TITLE
Uncaught ErrorException: Use of undefined constant GLOB_BRACE - assumed 'GLOB_BRACE'

### ISSUE THREAD

**Issue by Reasno** [kakuilan/php-helper#1]
￼PHP Fatal error:  Uncaught ErrorException: Use of undefined constant GLOB_BRACE - assumed 'GLOB_BRACE' (this will throw an Error in a future version of PHP) in /home/jenkins/agent/workspace/dev/vendor/kakuilan/php-helper/src/Helpers/DirectoryHelper.php:52

**Comment by Reasno** [comment]
查了一下 在alpine上PHP没有这个常量

**Comment by kakuilan** [comment]
若在线,更新v0.2.3再试下.我这边始终拉不了php:alpine镜像;
只是检测了下常量,不行明天我再看看.

**Comment by kakuilan** [comment]
不行,alpine下glob和bcadd函数都受影响,看样子只能抽时间再处理了

**Comment by Reasno** [comment]
嗯嗯 辛苦 现在已经想办法绕过了，不急。

**Comment by kakuilan** [comment]
已修复
